DEBUG = True
FPS = 20
ASSETS_DIR = 'assets'
HOTAIR_BALLON_FILE = 'ballon_1.png'
HOTAIR_BALLON_SIZE = (100,100)
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
HOTAIR_BALLON_MIN_SPEED = 3
HOTAIR_BALLON_MAX_SPEED = 3


